version: "3.7"

services:

  db:
    image: library/postgres:12.1-alpine
    container_name: leaderboard_db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: leaderboard
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"


volumes:
  dbdata:
    driver: local